# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 470, 641, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(-5, 20, 651, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 0, 481, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.detectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.detectButton.setGeometry(QtCore.QRect(270, 290, 93, 28))
        self.detectButton.setObjectName("detectButton")
        self.resetButton = QtWidgets.QPushButton(self.groupBox_2)
        self.resetButton.setGeometry(QtCore.QRect(380, 290, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 50, 72, 15))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(250, 50, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 120, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(640, 340, 481, 331))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 641, 461))
        self.groupBox_4.setObjectName("groupBox_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView.setGeometry(QtCore.QRect(0, 20, 641, 441))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuimage_mode = QtWidgets.QMenu(self.menu)
        self.menuimage_mode.setObjectName("menuimage_mode")
        self.menuvideo_mode = QtWidgets.QMenu(self.menu)
        self.menuvideo_mode.setObjectName("menuvideo_mode")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondensity_setting = QtWidgets.QAction(MainWindow)
        self.actiondensity_setting.setObjectName("actiondensity_setting")
        self.actionglobal_setting = QtWidgets.QAction(MainWindow)
        self.actionglobal_setting.setObjectName("actionglobal_setting")
        self.actionweight_setting = QtWidgets.QAction(MainWindow)
        self.actionweight_setting.setObjectName("actionweight_setting")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionopen_singe_image = QtWidgets.QAction(MainWindow)
        self.actionopen_singe_image.setObjectName("actionopen_singe_image")
        self.actionopen_a_directory_for_detect = QtWidgets.QAction(MainWindow)
        self.actionopen_a_directory_for_detect.setObjectName("actionopen_a_directory_for_detect")
        self.actioncommon_setting = QtWidgets.QAction(MainWindow)
        self.actioncommon_setting.setObjectName("actioncommon_setting")
        self.actionuse_camera_as_input = QtWidgets.QAction(MainWindow)
        self.actionuse_camera_as_input.setObjectName("actionuse_camera_as_input")
        self.actionuse_video_file_as_input = QtWidgets.QAction(MainWindow)
        self.actionuse_video_file_as_input.setObjectName("actionuse_video_file_as_input")
        self.menuimage_mode.addAction(self.actionopen_singe_image)
        self.menuimage_mode.addAction(self.actionopen_a_directory_for_detect)
        self.menuvideo_mode.addAction(self.actionuse_camera_as_input)
        self.menuvideo_mode.addAction(self.actionuse_video_file_as_input)
        self.menu.addAction(self.menuimage_mode.menuAction())
        self.menu.addAction(self.menuvideo_mode.menuAction())
        self.menu_2.addAction(self.actioncommon_setting)
        self.menu_3.addAction(self.actionabout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "状态显示区域"))
        self.groupBox_2.setTitle(_translate("MainWindow", "启动设置"))
        self.detectButton.setText(_translate("MainWindow", "开始检测"))
        self.resetButton.setText(_translate("MainWindow", "重置"))
        self.label.setText(_translate("MainWindow", "选择模型"))
        self.label_2.setText(_translate("MainWindow", "选择斑马线种类"))
        self.groupBox.setTitle(_translate("MainWindow", "结果显示区域"))
        self.groupBox_4.setTitle(_translate("MainWindow", "图片视频显示区域"))
        self.menu.setTitle(_translate("MainWindow", "模式选择"))
        self.menuimage_mode.setTitle(_translate("MainWindow", "image mode"))
        self.menuvideo_mode.setTitle(_translate("MainWindow", "video mode"))
        self.menu_2.setTitle(_translate("MainWindow", "参数设置"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actiondensity_setting.setText(_translate("MainWindow", "density setting"))
        self.actionglobal_setting.setText(_translate("MainWindow", "global setting"))
        self.actionweight_setting.setText(_translate("MainWindow", "weight setting"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionopen_singe_image.setText(_translate("MainWindow", "open singe image"))
        self.actionopen_a_directory_for_detect.setText(_translate("MainWindow", "open a directory for detect"))
        self.actioncommon_setting.setText(_translate("MainWindow", "common setting"))
        self.actionuse_camera_as_input.setText(_translate("MainWindow", "use camera as input"))
        self.actionuse_video_file_as_input.setText(_translate("MainWindow", "use video file as input"))


