# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 695)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 571, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.label_5.setObjectName("label_5")
        self.one_zebra = QtWidgets.QLineEdit(self.groupBox)
        self.one_zebra.setGeometry(QtCore.QRect(290, 40, 113, 21))
        self.one_zebra.setObjectName("one_zebra")
        self.triangle_zebra = QtWidgets.QLineEdit(self.groupBox)
        self.triangle_zebra.setGeometry(QtCore.QRect(290, 80, 113, 21))
        self.triangle_zebra.setObjectName("triangle_zebra")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.label_6.setObjectName("label_6")
        self.rectangle_zebra = QtWidgets.QLineEdit(self.groupBox)
        self.rectangle_zebra.setGeometry(QtCore.QRect(290, 130, 113, 21))
        self.rectangle_zebra.setObjectName("rectangle_zebra")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 211, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 571, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 72, 15))
        self.label_4.setObjectName("label_4")
        self.person_weight = QtWidgets.QLineEdit(self.groupBox_2)
        self.person_weight.setGeometry(QtCore.QRect(160, 30, 113, 21))
        self.person_weight.setObjectName("person_weight")
        self.bike_weight = QtWidgets.QLineEdit(self.groupBox_2)
        self.bike_weight.setGeometry(QtCore.QRect(160, 70, 113, 21))
        self.bike_weight.setObjectName("bike_weight")
        self.pet_weight = QtWidgets.QLineEdit(self.groupBox_2)
        self.pet_weight.setGeometry(QtCore.QRect(160, 110, 113, 21))
        self.pet_weight.setObjectName("pet_weight")
        self.car_weight = QtWidgets.QLineEdit(self.groupBox_2)
        self.car_weight.setGeometry(QtCore.QRect(160, 150, 113, 21))
        self.car_weight.setObjectName("car_weight")
        self.confirmBtn = QtWidgets.QPushButton(Dialog)
        self.confirmBtn.setGeometry(QtCore.QRect(410, 650, 93, 28))
        self.confirmBtn.setObjectName("confirmBtn")
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(510, 650, 93, 28))
        self.cancelBtn.setObjectName("cancelBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 390, 571, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 131, 16))
        self.label_8.setObjectName("label_8")
        self.default_result_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.default_result_path.setGeometry(QtCore.QRect(160, 40, 261, 21))
        self.default_result_path.setObjectName("default_result_path")
        self.choose_result_path_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.choose_result_path_btn.setGeometry(QtCore.QRect(450, 40, 93, 28))
        self.choose_result_path_btn.setObjectName("choose_result_path_btn")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 171, 16))
        self.label_9.setObjectName("label_9")
        self.max_image_num = QtWidgets.QLineEdit(self.groupBox_3)
        self.max_image_num.setGeometry(QtCore.QRect(240, 90, 113, 21))
        self.max_image_num.setObjectName("max_image_num")
        self.default_result_text = QtWidgets.QLineEdit(self.groupBox_3)
        self.default_result_text.setGeometry(QtCore.QRect(160, 140, 261, 21))
        self.default_result_text.setObjectName("default_result_text")
        self.choose_result_text_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.choose_result_text_btn.setGeometry(QtCore.QRect(450, 140, 93, 28))
        self.choose_result_text_btn.setObjectName("choose_result_text_btn")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 140, 131, 16))
        self.label_10.setObjectName("label_10")
        self.default_result_html = QtWidgets.QLineEdit(self.groupBox_3)
        self.default_result_html.setGeometry(QtCore.QRect(160, 190, 261, 21))
        self.default_result_html.setObjectName("default_result_html")
        self.choose_result_html_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.choose_result_html_btn.setGeometry(QtCore.QRect(450, 190, 93, 28))
        self.choose_result_html_btn.setObjectName("choose_result_html_btn")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 131, 16))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "密度相关设置"))
        self.label_5.setText(_translate("Dialog", "当前最大密度：单行斑马线"))
        self.label_6.setText(_translate("Dialog", "当前最大密度：三岔路斑马线"))
        self.label_7.setText(_translate("Dialog", "当前最大密度：十字路斑马线"))
        self.groupBox_2.setTitle(_translate("Dialog", "权重相关设置"))
        self.label.setText(_translate("Dialog", "person"))
        self.label_2.setText(_translate("Dialog", "bike"))
        self.label_3.setText(_translate("Dialog", "pet"))
        self.label_4.setText(_translate("Dialog", "car"))
        self.confirmBtn.setText(_translate("Dialog", "确认设置"))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
        self.groupBox_3.setTitle(_translate("Dialog", "全局设置"))
        self.label_8.setText(_translate("Dialog", "默认结果存储路径"))
        self.choose_result_path_btn.setText(_translate("Dialog", "重新选择"))
        self.label_9.setText(_translate("Dialog", "默认摄像头截取图片数目"))
        self.choose_result_text_btn.setText(_translate("Dialog", "重新选择"))
        self.label_10.setText(_translate("Dialog", "默认json存储路径"))
        self.choose_result_html_btn.setText(_translate("Dialog", "重新选择"))
        self.label_11.setText(_translate("Dialog", "结果html存储路径"))


